/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    ArtButton: typeof import('./../components/Art/Button/ArtButton.vue')['default']
    ArtLogo: typeof import('./../components/Art/Logo/ArtLogo.vue')['default']
    ArtPattern: typeof import('./../components/Art/Background/ArtPattern.vue')['default']
    Aurora: typeof import('./../components/Art/Background/Aurora.vue')['default']
    Canvas: typeof import('./../../../shared/components/canvas/index.vue')['default']
    CaptchaInput: typeof import('./../../../shared/components/input/CaptchaInput.vue')['default']
    Container: typeof import('./../components/Container/Container.vue')['default']
    FuncBtns: typeof import('./../components/FuncBtns/FuncBtns.vue')['default']
    Hyperspeed: typeof import('./../components/Art/Background/Hyperspeed.vue')['default']
    LogoutDialog: typeof import('./../../../shared/components/dialog/LogoutDialog.vue')['default']
    Menu: typeof import('./../components/menu/Menu.vue')['default']
    Navigation: typeof import('./../components/navigation/Navigation.vue')['default']
    ReadonlyInput: typeof import('./../../../shared/components/input/ReadonlyInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('./../components/ScrollTop/ScrollTop.vue')['default']
    SearchBtn: typeof import('./../components/FuncBtns/SearchBtn.vue')['default']
    SMSInput: typeof import('./../../../shared/components/input/SMSInput.vue')['default']
    SplashCursor: typeof import('./../components/Art/Animations/SplashCursor.vue')['default']
    SplitTitle: typeof import('./../components/Art/Title/SplitTitle.vue')['default']
    TextType: typeof import('./../components/Art/Title/TextType.vue')['default']
    ThumbsUp: typeof import('./../components/ThumbsUp/ThumbsUp.vue')['default']
    VectorField: typeof import('./../components/Art/VectorField/VectorField.vue')['default']
    Waves: typeof import('./../components/waves/Waves.vue')['default']
    ZBtn: typeof import('./../../../shared/components/btn/ZBtn.vue')['default']
    ZBtnToggle: typeof import('./../../../shared/components/btn/ZBtnToggle.vue')['default']
    ZCheckbox: typeof import('./../../../shared/components/checkbox/ZCheckbox.vue')['default']
    ZDialog: typeof import('./../../../shared/components/dialog/ZDialog.vue')['default']
    ZDragUpload: typeof import('./../../../shared/components/upload/ZDragUpload.vue')['default']
    ZEmpty: typeof import('./../../../shared/components/empty/ZEmpty.vue')['default']
    ZIconBtn: typeof import('./../../../shared/components/btn/ZIconBtn.vue')['default']
    ZImg: typeof import('./../../../shared/components/img/ZImg.vue')['default']
    ZInfo: typeof import('./../../../shared/components/info/ZInfo.vue')['default']
    ZInput: typeof import('./../../../shared/components/input/ZInput.vue')['default']
    ZLabel: typeof import('./../../../shared/components/label/ZLabel.vue')['default']
    ZLoading: typeof import('./../../../shared/components/loading/ZLoading.vue')['default']
    ZRadio: typeof import('./../../../shared/components/radio/ZRadio.vue')['default']
    ZSelect: typeof import('./../../../shared/components/select/ZSelect.vue')['default']
    ZTable: typeof import('./../../../shared/components/table/ZTable.vue')['default']
    ZTabs: typeof import('./../../../shared/components/tabs/ZTabs.vue')['default']
    ZTextBtn: typeof import('./../../../shared/components/btn/ZTextBtn.vue')['default']
    ZUpload: typeof import('./../../../shared/components/upload/ZUpload.vue')['default']
  }
}
