/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountStatus: typeof import('./../components/status/AccountStatus.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppSidebar: typeof import('./../components/AppSidebar.vue')['default']
    CaptchaInput: typeof import('./../../../shared/components/input/CaptchaInput.vue')['default']
    Empty: typeof import('./../components/empty/index.vue')['default']
    HintMessageItem: typeof import('./../components/item/HintMessageItem.vue')['default']
    HomeMenu: typeof import('./../components/menu/HomeMenu.vue')['default']
    LogoutDialog: typeof import('./../../../shared/components/dialog/LogoutDialog.vue')['default']
    MenuItem: typeof import('./../components/menu/MenuItem.vue')['default']
    QTab: typeof import('quasar')['QTab']
    QTabs: typeof import('quasar')['QTabs']
    ReadonlyInput: typeof import('./../../../shared/components/input/ReadonlyInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SMSInput: typeof import('./../../../shared/components/input/SMSInput.vue')['default']
    SubLabel: typeof import('./../components/label/SubLabel.vue')['default']
    TextBtn: typeof import('./../../../shared/components/btn/TextBtn.vue')['default']
    ZBtn: typeof import('./../../../shared/components/btn/ZBtn.vue')['default']
    ZBtnToggle: typeof import('./../../../shared/components/btn/ZBtnToggle.vue')['default']
    ZDialog: typeof import('./../../../shared/components/dialog/ZDialog.vue')['default']
    ZDragUpload: typeof import('./../../../shared/components/upload/ZDragUpload.vue')['default']
    ZInput: typeof import('./../../../shared/components/input/ZInput.vue')['default']
    ZLabel: typeof import('./../../../shared/components/label/ZLabel.vue')['default']
    ZLoading: typeof import('./../../../shared/components/loading/ZLoading.vue')['default']
    ZRadio: typeof import('./../../../shared/components/radio/ZRadio.vue')['default']
    ZSelect: typeof import('./../../../shared/components/select/ZSelect.vue')['default']
    ZTable: typeof import('./../components/table/ZTable.vue')['default']
    ZUpload: typeof import('./../../../shared/components/upload/ZUpload.vue')['default']
  }
}
